services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: portfolio-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/public
      - /app/.nuxt
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
