function pick (
  source: NodeJS.ProcessEnv,
  keys: Array<string>,
): Partial<NodeJS.ProcessEnv> {
  return keys.reduce((picked, key) => ({ ...picked, [key]: source[key] }), {})
}

export const env = pick(process.env, [
  'PORTFOLIO_REPOSITORY',
  'DOCK_REPOSITORY',
  'DOCK_NPM_URL',
  'LIBRARY_SYSTEM_REPOSITORY',
  'LIBRARY_SYSTEM_URL',
  'SIMPLE_CALCULATOR_REPOSITORY',
  'SIMPLE_CIRCUIT_CALCULATOR_REPOSITORY',
  'OHMS_LAW_CALCULATOR_REPOSITORY',
  'PYTHON_CHALLENGES_REPOSITORY',
  'ONESIMO_FOUNDATION_LINK',
  'ONESIMO_FOUNDATION_CHANGE_TRAILER_LINK',
  'ONESIMO_FOUNDATION_CHANGE_FILM_LINK',
  'CPU_SCHEDULING_SIMULATOR_REPOSITORY',
  'CPU_SCHEDULING_SIMULATOR_URL',
  'CASA_BURGOS_LINK',
  'KEYWEST_INTERNATIONALE_LINK',
  'CRANE_PHILIPPINES_LINK',
  'OPTIMUM_INDUSTRIAL_LINK',
  'RUSTIC_TABLE_LINK',
  'RAIN_3D_ANIMATION_LINK',
  'WINE_3D_ANIMATION_LINK',
  'PLASMA_3D_ANIMATION_LINK',
  'FEU_TECH_LINK',
  'CODE_NINJA_LINK',
  'IMPORTGENIUS_LINK',
])
