#!/usr/bin/env bash

CI_REPOSITORY_URL=$1
REQUIRED_TAG_SOURCE=$2
CI_BRANCH=$3
REQUIRED_TAG_SOURCE_BRANCH=required-tag-source-branch

git fetch $CI_REPOSITORY_URL $REQUIRED_TAG_SOURCE:$REQUIRED_TAG_SOURCE_BRANCH > /dev/null 2>&1
git log $REQUIRED_TAG_SOURCE_BRANCH...$CI_BRANCH
git branch -d $REQUIRED_TAG_SOURCE_BRANCH > /dev/null 2>&1
