FROM node:16-alpine

# Install build dependencies (needed for compiling native modules like sharp on alpine)
RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

EXPOSE 3000

CMD ["sleep", "infinity"]
