FROM alpine:3.24.1

WORKDIR /app

RUN apk add --no-cache libc6-compat python3 make g++ git
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/v3.16/main/ \
  nodejs=16.20.2-r0 npm
RUN npm install -g yarn

EXPOSE 3000

CMD ["sleep", "infinity"]
