import { mapReferencedProjects, LinkName } from '~/lib/config/profile/projects'
import { requireProgressiveImage } from '~/lib/config'

export const kata = mapReferencedProjects([
  {
    name: 'Java Kata',
    key: 'java-kata',
    period: 'Present',
    tags: [
      'Java',
      'Codewars',
      'TDD',
      'Big O',
      'kata',
      'data',
      'structures',
      'algorithm',
    ],
    description: 'Collection of Java kata challenges.',
    images: ['./assets/images/projects/java-kata/java-kata.png'].map(requireProgressiveImage),
    technologies: ['java'],
    featured: true,
    secondaryLink: {
      text: LinkName.VIEW_SOURCE,
      link: process.env.JAVA_KATA_REPOSITORY,
      linkIcon: 'mdiGithub',
    },
  },
  {
    name: 'Go Kata',
    key: 'go-kata',
    period: 'Present',
    tags: [
      'Go',
      'Codewars',
      'TDD',
      'Big O',
      'kata',
      'data',
      'structures',
      'algorithm',
    ],
    description: 'Collection of Go kata challenges.',
    images: ['./assets/images/projects/go-kata/go-kata.png'].map(requireProgressiveImage),
    technologies: ['go'],
    featured: true,
    secondaryLink: {
      text: LinkName.VIEW_SOURCE,
      link: process.env.GO_KATA_REPOSITORY,
      linkIcon: 'mdiGithub',
    },
  },
  {
    name: 'TypeScript Challenges',
    key: 'typescript-challenges',
    period: '2021 October',
    tags: [
      'TypeScript',
      'Node.js Notebooks',
      'kata',
      'types',
      'intellisense',
    ],
    description: 'Collection of TypeScript type challenges for practice with Node.js Notebooks.',
    images: [
      './assets/images/projects/typescript-challenges/readme.png',
      './assets/images/projects/typescript-challenges/initial.png',
      './assets/images/projects/typescript-challenges/half-solved.png',
      './assets/images/projects/typescript-challenges/solved.png',
    ].map(requireProgressiveImage),
    technologies: [
      'typescript',
      'node-js',
      'vs-code',
    ],
    secondaryLink: {
      text: LinkName.VIEW_SOURCE,
      link: process.env.TYPESCRIPT_CHALLENGES_REPOSITORY,
      linkIcon: 'mdiGitlab',
    },
  },
  {
    name: 'Python Challenges',
    key: 'python-challenges',
    period: '2019 May',
    tags: [
      'Python',
      'kata',
      'data',
      'structures',
      'regular',
      `expressions`,
      'design',
      'patterns',
    ],
    description: 'Collection of various coding challenge answers - exploring python basics, data structures, regular expressions and design patterns.',
    images: [
      './assets/images/projects/python-challenges/root.png',
      './assets/images/projects/python-challenges/navigation.png',
      './assets/images/projects/python-challenges/design-pattern-directory.png',
      './assets/images/projects/python-challenges/design-pattern-challenge.png',
      './assets/images/projects/python-challenges/data-structure-directory.png',
      './assets/images/projects/python-challenges/data-structure-challenge.png',
    ].map(requireProgressiveImage),
    technologies: ['python'],
    secondaryLink: {
      text: LinkName.VIEW_SOURCE,
      link: process.env.PYTHON_CHALLENGES_REPOSITORY,
      linkIcon: 'mdiGitlab',
    },
  },
])
